### PR TITLE
Tools: Updated Ubuntu prereqs with currently used gcc

### PR DESCRIPTION
**Pull request by AndKe**

### CODE REVIEW

**Comment by magicrub** [comment]
This needs a bit of scrutiny by the community, @tridge in particular. Nothing is wrong with our current g++ compiler so upgrading from 4.7 to 4.8 only brings mystery.

**Comment by AndKe** [comment]
In such case, I would agree, but Tridge told me today that we're supposed to use 4.8,  I assumed q3

**Comment by AndKe** [comment]
Oops , sorry - that was billbonney , I hope @tridge can shed some light on this as well :)

**Comment by AndKe** [comment]
I just discovered that using the 4.8 2014q3 version , I get this error:
```
/home/andre/prog/ardupilot/libraries/AP_NavEKF/AP_NavEKF.cpp:1871:1: error: the frame size of 1200 bytes is larger than 1024 bytes [-Werror=frame-larger-than=]
 }
 ^
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

This is very strange knowing that I used the version before on another system, and just now upgraded this one (both Ubuntu) 
Please do NOT pull this PR until we are sure 4.8 Q3 is supposed to work.

**Comment by billbonney** [comment]
reference to https://groups.google.com/d/msg/drones-discuss/-NB-9Bq4T2Q/MAiQZ2vbMhcJ about using 4.8, but that was for AVR, but I assume the same for gcc. I have build with gcc version 4.9 on RPi with success.

**Comment by gmorph** [comment]
I'm clarifying for everyone the officially supported compiler versions for ArduPilot at the time of writing:
For APM2 we are using avr-gcc version 4.8.2
For PX4/Pixhawks we are using arm-none-eabi-gcc v4.7.4 
We do want to move to a newer version of the ARM compiler but we haven't done that work yet.
Thanks, Grant.

**Comment by magicrub** [comment]
So @gmorph, are you saying we should close this for now or just push it off for further testing? @Tridge?

**Comment by gmorph** [comment]
We do want/need to do it.  It will be done.  We just aren't going to do it this second and we might jump to 4.9 or later.  So I don't think this PR will be merged as is so I would close it.

**Comment by tridge** [comment]
I have bench tested using 4.8 and it is no problem, just needs a flight test

**Comment by rmackay9** [comment]
if someone pings me a binary I'm happy to give it a quick flight test.

**Comment by AndKe** [comment]
@rmackay9 is it master or a specific milestone you would like to ? -  and for Pixhawk ?

(I have gcc-arm-none-eabi-4_8-2014q3 installed, and have been flying it around the time I reported and tried to find the speed change bug.)

**Comment by rmackay9** [comment]
@AndKe,
master for a quad would be a-ok.

**Comment by AndKe** [comment]
@rmackay9  a Pixhawk build is now here : https://drive.google.com/file/d/0B3E4K1nvpDuFYTBmY1I3TnlqNWc/view?usp=sharing

in case of something strange it does have md5 28dc8a41a11e2b6a2ebf0001f5eabe9e  ArduCopter-v2-quad , gcc4_8_2014-q3.px4

- It's current master, but with a fix for https://github.com/diydrones/ardupilot/issues/2480
I planned to test it tomorrow  . if you wish to test, and if it I works, I can make a PR this evening :)

To test , have a WPNAV_SPEED set to something fast   - fly a mission that sets speed to 1m/s , trigger RTL.  Expected speed in RTL would then be WPNAV_SPEED

I don't really ask YOU to test for me  :)   - but mentioning it just in case...  I don't think you'd expect a binary equal output that 4.7 gave anyway :)

**Comment by rmackay9** [comment]
I've flight tested the binary from @AndKe and it flew a-ok.
@tridge said above that that was the final requirement so maybe we're good to pull this into master now?  I can do that pull but maybe one last check with Tridge..

**Comment by lucasdemarchi** [comment]
We are already in 4.9.3 and it's installing in the ubuntu scripts as required. Closing.
